name: Build check
on: [ push ]

jobs:
  build:
    name: Build boot images
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/zbm-dev/zbm-builder
    steps:
      - uses: actions/checkout@master

      - name: Build artifacts
        run: |
          ln -s "$(pwd)" /zbm
          cp /zbm/etc/zfsbootmenu/release.conf.d/release.conf /zbm/etc/zfsbootmenu/dracut.conf.d/
          /zbm/releng/docker/zbm-build.sh -e '.Global.DracutFlags += ["--no-early-microcode"]' -- --debug

      - name: Archive EFI
        uses: actions/upload-artifact@v2
        with:
          name: EFI
          path: /zbm/releng/docker/build/*.EFI

      - name: Archive components
        uses: actions/upload-artifact@v2
        with:
          name: Components
          path: |
            /zbm/releng/docker/build/*
            !/zbm/releng/docker/build/*.EFI
